stages:
  - test # Runs written tests
  - build # Create a deploy build

Unit:
  stage: test
  image: rust:1.64.0-alpine3.16
  before_script:
    - apt-get update
    - apt-get install pkg-config libssl-dev -y
  script:
    - cargo test

RC:
  stage: build
  image: rust:1.64.0-alpine3.16
  before_script:
    - apt-get update
    - apt-get install pkg-config libssl-dev -y
  script:
    - cargo build --release