version: '3.1'

services:
  mongo:
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  api:
    image: dziro_api:0.1.0
    ports:
      - 80:8888
    env_file:
      - ../.env